name: Auto-close PR
on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  close:
    name: Run
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - run: |
          gh pr close ${{ github.event.pull_request.number }} --comment \
          "At the moment we are not accepting contributions to the repository.

          Feedback for GitHub Copilot for Xcode can be given in the [Copilot community discussions](https://github.com/orgs/community/discussions/categories/copilot)."
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
[![CodeQL Advanced](https://github.com/noprodnsspeed-us-kg/-CopilotForXcode-/actions/workflows/codeql.yml/badge.svg?event=deployment)](https://github.com/noprodnsspeed-us-kg/-CopilotForXcode-/actions/workflows/codeql.yml)
